### ISSUE TITLE
Export all available data tab separated gives error

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#10]
![Screenshot 2022-02-07 at 13-48-35 Voyant Tools](https://user-images.githubusercontent.com/24277755/152798097-a51873af-32a6-4f0d-b97a-099355803012.png)

gives the following error
![Screenshot 2022-02-07 at 13-49-10 Screenshot](https://user-images.githubusercontent.com/24277755/152798167-3833e1f2-f4c7-44f5-ae02-cd55a330e197.png)

**Comment by ajmacdonald** [comment]
Can you please provide more details, i.e. the tool you were exporting from and the corpus you were using?

**Comment by ajmacdonald** [comment]
Unfortunately I can't reproduce the error.
Additionally, the tab separated values export option should not produce JSON so I don't yet understand how you're getting this error.

**Comment by pbstudent** [comment]
This has been a consistent error for many versions of Voyant Server when using Firefox. I tested Chrome and I do not get the error. Testing on Safari produced the following display:
![2022-02-08_07-50-49](https://user-images.githubusercontent.com/24277755/152933849-755a49ec-3548-4a3f-9905-42f8c274e597.jpg)

It appears that Voyant Server works best with Chrome.

**Comment by ajmacdonald** [comment]
I've tried to reproduce your issue in Safari (13.1.2) and have been unable to.

**Comment by ajmacdonald** [comment]
This fixes the Firefox/JSON issue but it won't be available in VoyantServer until I create a new release: https://github.com/voyanttools/Voyant/commit/2347cf491195cbb32f42051e1d3e0d89b263c0ed

**Comment by pbstudent** [comment]
Thank you very much for the fix.

Safari 15.3 - display issue appears in this version.
Safari 10.1.2 displays correctly.

**Comment by ajmacdonald** [comment]
I looked into it and the issue with newer Safari versions is due to incompatibility with the framework that powers much of Voyant's frontend.
Unfortunately a fix is unlikely. I suggest using Chrome or Firefox.

**Comment by pbstudent** [comment]
Good to know. May need to be considered for the Readme file as a known issue?

Thank you.
