### ISSUE TITLE
Voyant webpage error on startup

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#16]
Status: java 8 update 321; MacOS 12.3.1; M1 chip
(noteworthy that https://voyant-tools.org is a working alternative)

I get the following error on startup:

HTTP ERROR 500

Problem accessing /. Reason:

    Server Error

Caused by:

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 52 in the jsp file: /index.jsp
System cannot be resolved
49: 		config: {
50: 			baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},
[VTS error.txt](https://github.com/voyanttools/VoyantServer/files/8465581/VTS.error.txt)

**Comment by ajmacdonald** [comment]
Thanks for the error log. What OS are you using?

**Comment by pbstudent** [comment]
>  java 8 update 321; MacOS 12.3.1; M1 chip

**Comment by ajmacdonald** [comment]
Thanks. Would you be willing to retry it with Java 11?

**Comment by pbstudent** [comment]
1. uninstall java from https://javadl-esd-secure.oracle.com/update/jut/JavaUninstallTool.dmg
2. cleared directory at /Library/Java/JavaVirtualMachines/
3. installed jdk-11.0.13_osx-x64_bin.dmg from https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html
4. launched VoyantServer 2.5.4
5. worked as expected with no errors

Also worked:
zulu11.54.25-ca-jre11.0.14.1-macosx_aarch64.dmg from https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit

OpenJDK11U-jre_x64_mac_hotspot_11.0.14.1_1.pkg from https://adoptium.net/temurin/releases

**Comment by ajmacdonald** [comment]
Thank you for your extensive testing.
It's strange that VoyantServer was not working with jre-8u321 initially, but then did after you reinstalled it.
Java 18 is definitely not supported.

**Comment by pbstudent** [comment]
Testing involved starting from empty directory  /Library/Java/JavaVirtualMachines/
Previously there were several Java versions/folders in the /JavaVirtualMachines/ directory.
Multiple Java versions in the same directory appears to create problems for VoyantTools Server.

**Comment by pbstudent** [comment]
macOS 12.3.1 for Apple M1
