### ISSUE TITLE
Export PNG not working

### ISSUE THREAD

**Issue by ljpetkovic** [voyanttools/VoyantServer#17]
Hello, 

I read in the [documentation](https://griffithunilibrary.github.io/data-vis-basics/content/5-voyant.html) that it was possible to export the visualisations as PNG files.

However, I only see the possibility to export as URL (on both local and web version).
<img width="286" alt="Capture d’écran 2022-04-09 à 17 55 14" src="https://user-images.githubusercontent.com/42590315/162581639-07aa9818-44fc-4202-a251-449463d9409f.png">

**Comment by ajmacdonald** [comment]
Hello,
I'll try to help but I need from information from you:
What browser and OS are you using?
Are you using the online version of Voyant Tools or have you downloaded it from this repository?

**Comment by ljpetkovic** [comment]
I work on macOS Monterey (v. 12.2.1), Apple M1.
The bug appears in both the online version of Voyant Tools and on the local server enabled by downloading the zipped file [`VoyantServer2_5_4.zip`](https://github.com/voyanttools/VoyantServer/releases/tag/2.5.4) (after downloading, I launched the application by executing `java -jar VoyantServer.jar`).

**Comment by ljpetkovic** [comment]
> I work on macOS Monterey (v. 12.2.1), Apple M1.
> The bug appears in both the online version of Voyant Tools and on the local server enabled by downloading the zipped file [`VoyantServer2_5_4.zip`](https://github.com/voyanttools/VoyantServer/releases/tag/2.5.4) (after downloading, I launched the application by executing `java -jar VoyantServer.jar`).

**Comment by ljpetkovic** [comment]
It works in Firefox! (I tried only in Safari)

**Comment by ajmacdonald** [comment]
Thanks for the info.
The framework that's used for most of the UI is old and doesn't support newer versions of Safari, unfortunately.
