### ISSUE TITLE
Hover tooltips in Summary tool erroneous

### ISSUE THREAD

**Issue by stragu** [voyanttools/VoyantServer#18]
In the Summary tool, the user can hover over a string that is underlined with a dotted line to reveal a description.

Currently, all numbers have a "number of words in this document" tooltip, which is only correct for the "Document length" section, not the other ones.

Here are proposed strings for the other three sections:

* Vocabulary Density: "Vocabulary density for this document"
* Average Words Per Sentence: "Average words per sentence in this document"
* Readability Index: "Readability index for this document"

A bit repetitive, but at least accurate. The strings could give more information about the kind of measurement, but that might be something to keep for the documentation instead of the tooltip.

By the way, where would one look for amending those strings and submitting a pull request?

**Comment by ajmacdonald** [comment]
Thanks for pointing this out, and for the suggested replacements.

Unfortunately the localization source document for Voyant Tools exists outside of GitHub so you can't submit a pull request related to that.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/652b3a06d8c9227746ceb6c2704fdd1f7508b42c
