### ISSUE TITLE
Steamgraph Y axis frequencies

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#2]
Corpus Terms (https://voyant-tools.org/docs/#!/guide/corpusterms) explains relative frequencies. However, StreamGraph (https://voyant-tools.org/docs/#!/guide/streamgraph) does not explain how relative and raw frequencies are calculated. The only statement on Streamgraph frequencies is found in the server application - Streamgraph panel popup information that stated " relative frequencies are relative counts per document or segment. " Further information on meaning of frequencies would have been helpful in https://voyant-tools.org/docs/#!/guide/streamgraph .

The best references found thus far for stacked area graph are:

p.1249
Byron, L., & Wattenberg, M. (2008). Stacked graphs–geometry & aesthetics. IEEE Transactions on Visualization and Computer Graphics, 14(6), 1245–1252. https://www.cg.tuwien.ac.at/courses/InfoVis/papers/InfoVis2008%20Stacked%20Graphs%20-%20Geometry%20&%20Aesthetics%20[Byron].pdf

Havre, S., Hetzler, B., & Nowell, L. (2002). ThemeRiverTM: In search of trends, patterns, and relationships. IEEE Transactions on Visualization and Computer Graphics, 8(1), 9–20. https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.445.2423&rep=rep1&type=pdf

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/ca2f7ed3fe05080d12b362e29457c49b61e287f2
