### ISSUE TITLE
Version 2.6.0 crashes

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#25]
Version 2.5.4 works fine
Version 2.6.0 gives the following webpage 503 error:
![Screenshot 2022-08-11 at 22-05-56 Error 503](https://user-images.githubusercontent.com/24277755/184234304-b42bb2e5-d57b-4ab4-83ac-0204a10a868d.png)

Launching 2.6.0 produces displays the following app log:
[260.txt](https://github.com/voyanttools/VoyantServer/files/9311903/260.txt)

**Comment by ajmacdonald** [comment]
I've released a new version which I hope will fix these issues: https://github.com/voyanttools/VoyantServer/releases/tag/2.6.1
Please try it out and let me know.

**Comment by pbstudent** [comment]
Control: Server Version 2.5.4 works on all MacOS from 10.13

Confirmed to work under MacOS 10.13.6

Failed to work under MacOS 12.5.1 (M1, 2020)
[Webpage errors.txt](https://github.com/voyanttools/VoyantServer/files/9475850/Webpage.errors.txt)

[console errors.txt](https://github.com/voyanttools/VoyantServer/files/9475852/console.errors.txt)

**Comment by pbstudent** [comment]
Which version of Java to install (noting compatibility needed with LibreOffice) ?

**Comment by pbstudent** [comment]
I can confirm that version 2.6.1 works with MacOS 10.13.6 and up.
MacOS 10.13.6 using jdk1.8.0_221.jdk and jre-8u111-fcs-bin-b14-macosx-x86
MacOS 12.5.1 using jdk-11.0.16_macos-aarch64_bin and jre-8u341-macosx-x64

However, in the case of MacOS 12.5.1 the aforementioned configuration does not provide a URL for LibreOffice > advanced > java runtime ; whereas installing jdk-18_macos-aarch64_bin does but causes Voyant Server to fail.

**Comment by pbstudent** [comment]
After some testing I can confirm the following log errors are due to JDK versions:
[Webpage errors.txt](https://github.com/voyanttools/VoyantServer/files/9476466/Webpage.errors.txt)
[console errors.txt](https://github.com/voyanttools/VoyantServer/files/9476467/console.errors.txt)

If I install latest JDK (jdk-18_macos-aarch64_bin) I get the aforementioned errors.
<img width="552" alt="2022-09-02_10-44-38" src="https://user-images.githubusercontent.com/24277755/188102532-48483cd6-d32a-4535-a4bb-13b44ade9da8.png">

Then I remove the JDK 18 folder from  /Library/Java/JavaVirtualMachines/ and I get the following console error:

*** Starting Voyant Server – Web page will open automatically when ready **
Using Free AdminPort=34000
Cannot run program "/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/bin/java": error=2, No such file or directory

I then stop the server, quit, then restart and everything works.

**Comment by pbstudent** [comment]
A temporary solution to have both LibreOffice and Voyant Tools, is to move the folder **jdk-18.0.2.1.jdk** from /Library/Java/JavaVirtualMachines/  to /Users/username/Library/Application Support/Java/ . Then relocate path URL in LibreOffice.

This way both JDK can operate without conflicts between Voyant Tools and LibreOffice.

**Comment by pbstudent** [comment]
Confirming that Voyant Server 2.6.2 works correctly with Java - jdk-11.0.16.1.jdk
![jdk works](https://user-images.githubusercontent.com/24277755/210185015-4add9e37-ddd7-45f2-be86-d3de07bb217b.jpg)
