### ISSUE TITLE
Running VoyantServer in path other than '/'

### ISSUE THREAD

**Issue by gavieira** [voyanttools/VoyantServer#26]
I've been trying to run Voyant Server in http://localhost:port/voyant. 

I thought that setting the 'uri_path' to '/voyant' would do the trick, but it seems I was wrong. Changing this value makes no difference and the web service keeps opening at http://localhost:port/

Is there some way to change this behavior? Thanks in advance!

**Comment by ajmacdonald** [comment]
Currently `uri_path` is for appending default arguments to the URL, e.g. `/?corpus=foobar`.

I'll add your feature request to the list. Not sure when I'll get to it though.

**Comment by ajmacdonald** [comment]
I've committed the feature and it's in the latest release.

https://github.com/voyanttools/VoyantServer/commit/4a9f1cda8cc0b906ac3d5dbd0381b95a1d584574
