### ISSUE TITLE
Calculations for distinctive words

### ISSUE THREAD

**Issue by quinnanya** [voyanttools/VoyantServer#31]
Apologies for this question, but I wasn't able to find the details in the user manual or figure out what's going on from the related Spyral documentation: what's going on behind the scenes for calculating the "distinctive words" as part of the summary panel? I can find information about how to use stopword lists with distinctive words, but not how they're calculated. Thanks for any pointers!

**Comment by ajmacdonald** [comment]
Distinctive words are calculated using [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf).
I'll add this information to the docs so that it's more clear.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/63515dc325be58174b01b8e1feb3719fd061dd97
