### ISSUE TITLE
Chinese pre-processing documentation?

### ISSUE THREAD

**Issue by quinnanya** [voyanttools/VoyantServer#32]
Hi, apologies for another documentation question! I was wondering if there's any notes you have (or could add to the documentation) about what pre-processing happens for Chinese text? I pre-segmented some text and then uploaded them to Voyant, and it looked like it segmented the text further. I was thinking it was single-character segmentation, but then it looked like there was at least one two-character sequence that was kept intact. And the stopword list includes a ton of multi-character terms, which would be a little odd if it was doing single-character segmentation (but maybe just an artifact of borrowing a list from somewhere else). Any insight as to what's happening behind the scenes would be tremendously helpful!

**Comment by ajmacdonald** [comment]
It might be related to this [issue](https://github.com/voyanttools/Voyant/issues/42).
Please try [manually setting the language to Chinese](https://github.com/voyanttools/Voyant/issues/42#issuecomment-1339716471) and see if that helps.

**Comment by quinnanya** [comment]
Interesting -- that other ticket was having the same issue we were, which ultimately led to the question. What's the library you're using for it? I'd be curious to read through its documentation with my students who are working with Chinese.

**Comment by ajmacdonald** [comment]
Here's the library that's currently being used: https://github.com/optimaize/language-detector
I've already made an issue to replace it but cannot say when I'll get to that: https://github.com/voyanttools/trombone/issues/20
