### ISSUE TITLE
Cannot start voyant in window 10

### ISSUE THREAD

**Issue by alfred-yp** [voyanttools/VoyantServer#35]
Got lot of similar error as below when connecting to server.

An error occurred at line: [54] in the jsp file: [/index.jsp]
System cannot be resolved
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>',
55: 			entitiesEnabled: <%= application.getInitParameter("entitiesenabled") %>
56: 		},
57: 		launch: function() {

**Comment by ajmacdonald** [comment]
Please ensure that you are using a version of Java no higher than 11 and let me know if the problem persists.

**Comment by alfred-yp** [comment]
Too much problem running in Windows, switch to running it on Linux. Work fine first time!
