### ISSUE TITLE
Citation consistency in titles

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#39]
There appears to be two different item types with different titles, as per example:

**APA**
Sinclair, S. & G. Rockwell. (2023). Contexts. Voyant Tools. Retrieved August 3, 2023, from https://voyant-tools.org/?view=Contexts&query=%22open%20source*%22&corpus=067ee494bb8319c530da25e2a6c177e4

**BibTeX**
@misc{voyanttools_1691062882230,
  title = {Voyant Tools Contexts},
  author = {Sinclair, Stéfan and Rockwell, Geoffrey},
  year = 2022,
  url = {https://voyant-tools.org/?view=Contexts&query=%22open%20source*%22&corpus=067ee494bb8319c530da25e2a6c177e4},
  urldate = {2023-08-03},
  publisher = {Voyant Tools},
  copyright = {CC BY 4.0},
  abstract = {Voyant Tools analysis of a corpus using the Contexts tool},
  language = {en},
}

**Comment by ajmacdonald** [comment]
Thanks for pointing this out.
To be consistent in this case the title for BibTeX should be Contexts.
However in the case where the user is citing the entire site and not a specific tool: should the title be Voyant Tools, or should the title field be omitted entirely? For APA and Chicago we're omitting the title and just providing the publisher/website name.
