### ISSUE TITLE
Error when loading built-in corpora

### ISSUE THREAD

**Issue by stragu** [voyanttools/VoyantServer#4]
I just tested the new 2.5.0 release and tried to load Austen's novels, but got the error:

> Failed attempt to create a corpus
> A corpus was specified but does not exist, could not be migrated and could not be recreated

Same thing with Shakespeare's.

Tested on:

* VoyantServer 2.5.0
* Ubuntu 18.04.6
* Firefox 94.0
* OpenJDK JRE 11.0.11+9-0ubuntu2~18.04

**Comment by ajmacdonald** [comment]
Ah good find, I obviously didn't extensively test the release.
I will be sure to include them in the next release. In the meantime you'll have to provide your own corpora.

**Comment by ajmacdonald** [comment]
I've replaced the current binary release with a version that includes the pre-set corpora.
Future releases will have it included automatically: https://github.com/voyanttools/VoyantServer/commit/ae6a5d8000a93e31e55ac49b925067eb5a6f7cad

**Comment by stragu** [comment]
Fabulous, thanks for the fix. I can confirmed it fixed in the current 2.5.0 binary.
Cheers!
