### ISSUE TITLE
SSL for Hosted Voyant Server

### ISSUE THREAD

**Issue by hachacha** [voyanttools/VoyantServer#41]
Is there a way to add SSL to our voyant server? I went through the documentation here: https://voyant-tools.org/docs/#!/guide/server
and through the github code to see if there was anything related to adding an SSL Cert to the server but could not find anything.
I have a cert and key generated but am not sure where to add them. 
How would I go about doing this?

**Comment by ajmacdonald** [comment]
Voyant has no built-in tools for that.
On the official server we're using [certbot](https://certbot.eff.org/). It handles cert generation and can be used to modify the server configuration files and setup cert renewal scripts.
