### ISSUE TITLE
Voyant Server Mac fails with error in webpage

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#44]
JDK 23
(noteworthy that latest Voyant Server version works with MacOS Sequoia (15.0) and “jdk-11.0.16.1.jdk” with security warnings)

Sample from console:
An error occurred at line: [54] in the jsp file: [/index.jsp]
System cannot be resolved
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>',
55: 			entitiesEnabled: <%= application.getInitParameter("entitiesenabled") %>
56: 		},
57: 		launch: function() {

Sample from webpage:
HTTP ERROR 500 org.apache.jasper.JasperException: Unable to compile class for JSP: An error occurred at line: [52] in the jsp file: [/index.jsp] System cannot be resolved 49: config: { 50: baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>', 51: version: '<%= application.getInitParameter("version") %>', 52: openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>', 53: allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>', 54: allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>', 55: entitiesEnabled: <%= application.getInitParameter("entitiesenabled") %> An error occurred at line: [52] in the jsp file: [/index.jsp] System cannot be resolved 49: config: { 50: baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>', 51: version: '<%= application.getInitParameter("version") %>', 52: openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>', 53: allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>', 54: allowDownload: '<%=

**Comment by ajmacdonald** [comment]
As you noted, Voyant only works with Java 11 at this time.

**Comment by pbstudent** [comment]
Would be nice to have a link to the relevant Java version in the Readme.md for us new users. Thanks

**Comment by ajmacdonald** [comment]
Thanks for the feedback. I've added more explicit instructions: https://github.com/voyanttools/VoyantServer/commit/33feb1328f83014a6e3baf586489391f7d6b3013
