### ISSUE TITLE
Exported Text Tab separated file breaks

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#7]
Exporting a context infrequently creates a plain text file that breaks across a single row when copy/past or plain text import into spreadsheet. Source text file for corpus created in AntFileConverter 2.0.
Appears to be a hidden character (revealed in import to Libre Calc at end of last row) that does not create a new line.

[Contexts-resources_original broken.txt](https://github.com/voyanttools/VoyantServer/files/7746901/Contexts-resources_original.broken.txt)
[Contexts-resources_fixed.txt](https://github.com/voyanttools/VoyantServer/files/7746903/Contexts-resources_fixed.txt)
.
Had to fix manually into spreadsheet, re-save as CSV then export to tab separated text to return to same plain text output as other contexts exports.

**Comment by pbstudent** [comment]
Better plain text document preparation for corpus - used Xpdftotext 4.03 (http://www.xpdfreader.com/download.html), not AntFileConverter 2.0 (https://www.laurenceanthony.net/software/antfileconverter/).

**Comment by ajmacdonald** [comment]
I was able to import the broken file into LibreOffice Calc with the following options:
![Screenshot 2022-01-25 144931](https://user-images.githubusercontent.com/882444/151048942-b6101ec1-bf31-49dc-a375-4afd5f71590e.png)
I had to uncheck "Space" and, crucially, clear the string delimiter textbox.

**Comment by pbstudent** [comment]
Thank you, I will re-test importing into LO calc the export results based on your configuration.

**Comment by pbstudent** [comment]
I confirm the same results with text export from context in Voyant Tools Server version 2.5.3

Please note, the README.md does not include version number of Voyant Server
